package kevindonati.Enum;

public enum Genere {
    NARRATIVA, FANTASY, FANTASCIENZA, HORROR, THRILLER, GIALLO, ROMANZOSTORICO, AVVENTURA, AZIONE, DISTOPICO, UTOPICO, ROMANCE, YOUNGADULT, NEWADULT, BIOGRAFIA, AUTOBIOGRAFIA, SAGGISTICA, FILOSOFIA, PSICOLOGIA, CRESCITAPERSONALE, ECONOMIA, POLITICA, STORIA, SCIENZA, TECNOLOGIA, INFORMATICA, ARTE, POESIA, TEATRO, UMORISMO, SATIRA, RELIGIONE, SPIRITUALITÀ, MISTERO, NOIR, WESTERN, CYBERPUNK, STEAMPUNK, GOTICO, EPISTOLARE, FIABA, MITOLOGIA, FUMETTO, MANGA, GRAPHICNOVEL;
}
